export interface ApplicationDeadline {
  id: string;
  title: string;
  institution: string;
  opens?: string;
  closes: string;
  note?: string;
  category: "university" | "tvet" | "funding" | "general";
}

/** Key 2026/2027 application windows — verify on official sites before applying. */
export const APPLICATION_DEADLINES: ApplicationDeadline[] = [
  {
    id: "caos",
    title: "CAO (KZN universities)",
    institution: "Central Applications Office",
    opens: "1 March 2026",
    closes: "30 September 2026",
    category: "general",
    note: "UKZN, DUT, UNIZULU and other KZN institutions via cao.ac.za.",
  },
  {
    id: "nsfas",
    title: "NSFAS bursary applications",
    institution: "NSFAS",
    opens: "September 2026",
    closes: "31 January 2027",
    category: "funding",
    note: "Apply early — funding is not automatic.",
  },
  {
    id: "unisa",
    title: "UNISA undergraduate applications",
    institution: "UNISA",
    opens: "August 2026",
    closes: "October 2026",
    category: "university",
  },
  {
    id: "uct",
    title: "UCT undergraduate applications",
    institution: "University of Cape Town",
    opens: "1 April 2026",
    closes: "31 July 2026",
    category: "university",
  },
  {
    id: "wits",
    title: "Wits undergraduate applications",
    institution: "University of the Witwatersrand",
    opens: "March 2026",
    closes: "30 September 2026",
    category: "university",
    note: "Health sciences and architecture often close 30 June.",
  },
  {
    id: "up",
    title: "UP undergraduate applications",
    institution: "University of Pretoria",
    opens: "1 April 2026",
    closes: "30 June 2026",
    category: "university",
  },
  {
    id: "uj",
    title: "UJ undergraduate applications",
    institution: "University of Johannesburg",
    opens: "1 April 2026",
    closes: "31 October 2026",
    category: "university",
  },
  {
    id: "stellenbosch",
    title: "Stellenbosch undergraduate applications",
    institution: "Stellenbosch University",
    opens: "1 April 2026",
    closes: "31 July 2026",
    category: "university",
  },
  {
    id: "nwu",
    title: "NWU undergraduate applications",
    institution: "North-West University",
    opens: "1 June 2026",
    closes: "31 August 2026",
    category: "university",
    note: "Selection programmes may close earlier (often 30 June).",
  },
  {
    id: "ukzn",
    title: "UKZN undergraduate applications",
    institution: "University of KwaZulu-Natal",
    opens: "1 March 2026",
    closes: "30 September 2026",
    category: "university",
    note: "Apply via CAO (cao.ac.za). Medicine and health sciences close 30 June.",
  },
  {
    id: "nmu",
    title: "NMU undergraduate applications",
    institution: "Nelson Mandela University",
    opens: "13 April 2026",
    closes: "30 September 2026",
    category: "university",
    note: "MBChB, pharmacy, nursing and radiography close earlier (typically 30 June).",
  },
  {
    id: "cput",
    title: "CPUT undergraduate applications",
    institution: "Cape Peninsula University of Technology",
    opens: "May 2026",
    closes: "30 September 2026",
    category: "university",
    note: "Health sciences and some faculties have earlier closing dates.",
  },
  {
    id: "tut",
    title: "TUT undergraduate applications",
    institution: "Tshwane University of Technology",
    opens: "3 April 2026",
    closes: "31 July 2026",
    category: "university",
  },
  {
    id: "dut",
    title: "DUT undergraduate applications",
    institution: "Durban University of Technology",
    opens: "1 March 2026",
    closes: "30 September 2026",
    category: "university",
    note: "Apply via CAO (cao.ac.za).",
  },
  {
    id: "ufs",
    title: "UFS undergraduate applications",
    institution: "University of the Free State",
    opens: "1 April 2026",
    closes: "30 September 2026",
    category: "university",
    note: "MBChB and health sciences close 31 May; nursing and social work often 31 July.",
  },
  {
    id: "univen",
    title: "UNIVEN undergraduate applications",
    institution: "University of Venda",
    opens: "1 April 2026",
    closes: "26 September 2026",
    category: "university",
  },
  {
    id: "spu",
    title: "SPU undergraduate applications",
    institution: "Sol Plaatje University",
    opens: "April 2026",
    closes: "31 October 2026",
    category: "university",
    note: "Late applications may be considered if space remains.",
  },
  {
    id: "wsu",
    title: "WSU undergraduate applications",
    institution: "Walter Sisulu University",
    opens: "1 June 2026",
    closes: "31 October 2026",
    category: "university",
    note: "Late placement may be available for applicants meeting minimum APS.",
  },
  {
    id: "rhodes",
    title: "Rhodes undergraduate applications",
    institution: "Rhodes University",
    opens: "1 April 2026",
    closes: "30 September 2026",
    category: "university",
    note: "Highly selective — apply early for residence consideration.",
  },
  {
    id: "uwc",
    title: "UWC undergraduate applications",
    institution: "University of the Western Cape",
    opens: "1 April 2026",
    closes: "30 September 2026",
    category: "university",
    note: "Free to apply. Dentistry and oral health programmes close 31 August.",
  },
  {
    id: "falsebay",
    title: "False Bay TVET applications",
    institution: "False Bay TVET College",
    opens: "August 2026",
    closes: "30 November 2026",
    category: "tvet",
    note: "Apply directly at falsebay.org.za. NCV and NATED programmes; late applications if space allows.",
  },
  {
    id: "eeetvet",
    title: "Ekurhuleni East TVET applications",
    institution: "Ekurhuleni East TVET College",
    opens: "August 2026",
    closes: "30 November 2026",
    category: "tvet",
    note: "Apply directly at eec.edu.za.",
  },
  {
    id: "coastalkzn",
    title: "Coastal KZN TVET applications",
    institution: "Coastal KZN TVET College",
    opens: "August 2026",
    closes: "30 November 2026",
    category: "tvet",
    note: "Apply directly at coastalkzn.co.za.",
  },
  {
    id: "southcape",
    title: "South Cape TVET applications",
    institution: "South Cape TVET College",
    opens: "August 2026",
    closes: "30 November 2026",
    category: "tvet",
    note: "Apply directly at sccollege.co.za.",
  },
  {
    id: "orbit",
    title: "Orbit TVET applications",
    institution: "Orbit TVET College",
    opens: "August 2026",
    closes: "30 November 2026",
    category: "tvet",
    note: "Apply directly at orbit.co.za.",
  },
  {
    id: "umfolozi",
    title: "Umfolozi TVET applications",
    institution: "Umfolozi TVET College",
    opens: "August 2026",
    closes: "30 November 2026",
    category: "tvet",
    note: "Apply directly at umfolozicollege.co.za.",
  },
  {
    id: "westcoast",
    title: "West Coast TVET applications",
    institution: "West Coast TVET College",
    opens: "August 2026",
    closes: "30 November 2026",
    category: "tvet",
    note: "Apply directly at westcoastcollege.co.za.",
  },
  {
    id: "matric-results",
    title: "NSC results release (expected)",
    institution: "DBE / IEB",
    closes: "Mid-January 2027",
    category: "general",
    note: "Use final results to confirm eligibility before accepting offers.",
  },
];
