"use client";

import type { MatchResults } from "@/lib/types";
import { bucketAps, bucketCount, trackEvent } from "@/lib/analytics";

interface PdfExportButtonProps {
  results: MatchResults;
  className?: string;
}

export default function PdfExportButton({ results, className = "" }: PdfExportButtonProps) {
  const exportPdf = () => {
    trackEvent("pdf_export", {
      aps_bucket: bucketAps(results.studentAps),
      matches: bucketCount(results.totalPrograms),
    });

    const lines: string[] = [
      "AdmitScore — Your University Match Report",
      `APS Score: ${results.studentAps}/42`,
      `Total Matches: ${results.totalPrograms}`,
      "",
      `Safe Bets (${results.results.safeBets.length})`,
      ...results.results.safeBets.slice(0, 15).map((p) => `- ${p.programName} (${p.universityName}) — APS ${p.requiredAps}`),
      "",
      `Exact Matches (${results.results.exactMatches.length})`,
      ...results.results.exactMatches.slice(0, 15).map((p) => `- ${p.programName} (${p.universityName}) — APS ${p.requiredAps}`),
      "",
      `Near Misses (${results.results.nearMisses.length})`,
      ...results.results.nearMisses.slice(0, 15).map((p) => `- ${p.programName} (${p.universityName}) — need ${p.apsGap} more APS`),
      "",
      "Generated by AdmitScore — admitscore.co.za",
      "A product of MLK Computer Consulting — mlkcomputer.com",
    ];

    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `admitscore-results-${results.studentAps}-aps.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button type="button" onClick={exportPdf} className={`btn-secondary !py-2 !px-4 !text-xs ${className}`}>
      Download report
    </button>
  );
}
